n=int(input("Enter your Number : "))
i=1
k=1
while i<=n:
    b=1
    while b<=n-i:
        print(" ",end='')
        b=b+1
    j=1
    while j<=k:
        print(j,end='')
        j=j+1
    i=i+1
    k=k+2
    print()    
n=int(input("Enter your Number : "))
i=1
k=1
while i<=n:
    b=1
    while b<=n-i:
        print(" ",end='')
        b=b+1
    j=1
    while j<=k:
        print("*",end='')
        j=j+1
    i=i+1
    k=k+2
    print()        
n=int(input("Enter your Number : "))
i=1
k=1
while i<=n:
    b=1
    while b<=n-i:
        print(" ",end='')
        b=b+1
    j=1
    while j<=k:
        print(i,end='')
        j=j+1
    i=i+1
    k=k+2
    print()   
    n=int(input("Enter your Number : "))
i=1
k=1
while i<=n:
    b=1
    while b<=n-i:
        print(" ",end='')
        b=b+1
    j=1
    while j<=k:
        print(k,end='')
        j=j+1
    i=i+1
    k=k+2
    print()   